### PR TITLE
Populate Geometry/HGCalMapping with first version of the mapping files

### PR DESCRIPTION
**Pull request by pfs**
This PR populates the newly created repository with the first version of the files. 
The README.md is also updated with a minimal description and proposal of the versioning for now.

@kerstinlovisa

### CODE REVIEW

**Comment by srimanob** [comment]
+Upgrade

**Comment by pfs** [comment]
Thanks - it looks like the bot is waiting for someone with enough karma to issue a test command? If this can be integrated we can then proceed to update https://github.com/cms-sw/cmssw/pull/43751

**Comment by smuzaffar** [comment]
@pfs , first there is no need to create `data` sub directory. If you access these files as `Geometry/HGCalMapping/data/modulelocator_test.txt` (https://github.com/cms-sw/cmssw/pull/43751/files#diff-1c02ef59051ccce7b4d7b0b9c03cde85a1ff304e9a9abe928a9d3e41d76e5b95R6) then you need to just add `modulelocator_test.txt` in this repository ( instead of `data/ModuleMaps/v0/modulelocator_test.txt`).  If you want to keep these files under a sub directory e.g. `ModuleMaps` then please update https://github.com/cms-sw/cmssw/pull/43751 PR to use `Geometry/HGCalMapping/data/ModuleMaps/modulelocator_test.txt`. 

Are there any plans to have multiple version of these files with in same cmssw release? If yes then create a version sub-directory is fine but if only one version of this file is needed with in the CMSSW release then drop the `v0` sub-directory.

I would suggest to already update https://github.com/cms-sw/cmssw/pull/43751 ( remove the data files from there ) and start the testing from the cmssw PR.

**Comment by pfs** [comment]
hello @smuzaffar thanks for the suggestions. I prefer to keep the two separate folders {Cell,Module}Maps, but i removed the versioning and moved them to main directory.
The only different versions will happen for module maps, once we have the final optical fiber map and for test beam, but in the end it's preferrable to have these files with different names.
I'll update https://github.com/cms-sw/cmssw/pull/43751. How can i test with the changes of this PR?
thanks!

**Comment by aandvalenzuela** [comment]
Hello @pfs, you can test directly from https://github.com/cms-sw/cmssw/pull/43751 by typing `please test with <url to data PR>` as a comment when you are ready for testing

**Comment by pfs** [comment]
Ok i trigger the tests - hopefully it will work first time

**Comment by perrotta** [comment]
@pfs are these data files meant to be used only for tests *(now only accessed by Geometry/HGCalMapping/test/testMappingModuleIndexer_cfg.py in #43751)? If not, are they supposed to move eventually in the DB?

**Comment by pfs** [comment]
They will be eventually moved to conddb.

**Comment by pfs** [comment]
Hello - if no objections can this be merged?

**Comment by perrotta** [comment]
> Hello - if no objections can this be merged?

In principle yes, because they are all new files which won't affect current workflows. But why should we hurry up, and not merge it together with the accompanying CMSSW PR #43751, once ready?

**Comment by pfs** [comment]
ah ok, yes sounds good. We'll try to converge on  PR #43751 sometime next week after the hackathon - thanks

**Comment by antoniovilela** [comment]
merge

**Pull request merged**
